# Generated by Django 4.0.2 on 2022-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rate', models.IntegerField(choices=[(1, 'new'), (2, 'doing'), (3, 'done')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_punlished', models.BooleanField()),
                ('status', models.CharField(max_length=3)),
            ],
        ),
    ]
