# Generated by Django 4.0.2 on 2022-02-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
