# Generated by Django 4.0.2 on 2022-02-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='is_punlished',
            new_name='is_published',
        ),
    ]
